### ISSUE TITLE
Support German Umlauts

### ISSUE THREAD

**Issue by MarkejN** [MetaModels/filter_register#10]
I cannot use german umlauts in my application, because the filter link resolves to `/register/%E3%9C.html` instead of `/register/ü.html`. This results in an error (404). I think the solution is to use multibyte string functions?

https://github.com/MetaModels/filter_register/blob/dc12abbd5772dfbdebf5893a3d866dec116ae111/src/FilterSetting/Register.php#L129-L131

Change to:
```
$strFirstChar   = \mb_substr($strOptionValue, 0, 1);
$charUpperFist  = \mb_strtoupper($strFirstChar);
$charLowerFirst = \mb_strtolower($strFirstChar);
```

**Comment by zonky2** [comment]
Works fine in MM 2.2 - you cann add a PR for MM 2.1 or use MM 2.2 (see https://now.metamodel.me/de/unterstuetzer/fundraising#metamodels_2-2)
