### ISSUE TITLE
Attribut kann nicht ausgewählt weden im Filter-Modul

### ISSUE THREAD

**Issue by MacKP** [MetaModels/filter_register#5]
Dadurch kann kein Filter damit erstellt werden

**Comment by xantippe** [comment]
Im Panel für die Regeleinstellungen sieht alles prima aus

![shot43](https://cloud.githubusercontent.com/assets/1045318/12169189/5b59ec4e-b537-11e5-8a5d-22b900319693.jpg)

aber im CE-Metamoldels-Filter erscheint keine Checkbox zum Aktivieren
![shot44](https://cloud.githubusercontent.com/assets/1045318/12169206/7415b0a6-b537-11e5-88e1-8e1d84b06756.jpg)

getestet MM core 2.0.0-alpha8 und filter_register dev-master (03253ec4)

**Comment by xantippe** [comment]
damit der Filter als Attribut auftaucht, muss

```class Register extends Simple```
in 
```class Register extends SimpleLookup```

umgewandelt werden - dann werden die Checkboxen auch im Filter angezeigt - leider muss der restliche Teil von Register.php auch überarbeitet werden, da der Filter nicht funktioniert :-(

Die Optionen "Anzeige von Nummern" und "Leere Einträge verbergen" hat m.E. keine Auswirkung - für letzteres müsste eigentlich für jede Sprache ein Array mit den vorhandenen Buchstaben vorhanden sein...

![shot45](https://cloud.githubusercontent.com/assets/1045318/12171108/7b614b76-b547-11e5-9d54-f14b2910f291.jpg)

**Comment by stefanheimes** [comment]
First fix is in the current hotfix branch. Now it is possible to select the filter in the filter module again. 

The feature "Show numbers" and "Hide empty values" is bugy. So i have to correct it. 

But the filter works for me. I can select a char and the list filter in the right way.

**Comment by zonky2** [comment]
o.k. - the filter works now but I found two misstakes:

* after filtering, the checkbox at register character is´t checked

* the filter works as "AND" and should as "OR"

**Comment by zonky2** [comment]
> This feature should only be used as a single value filter and not as a multi value filter.

look at #7
