### ISSUE TITLE
Change the inputTyp to radio

### ISSUE THREAD

**Issue by stefanheimes** [MetaModels/filter_register#7]
This feature should only be used as a single value filter and not as a multi value filter.

See https://github.com/MetaModels/filter_register/blob/03253ec44ffe51fc98faf2d61a44a8090cd7e3a5/src/MetaModels/Filter/Setting/Register.php#L205

**Comment by zonky2** [comment]
@stefanheimes its possible to clean the bug?

**Comment by zonky2** [comment]
I had check this - the ```inputType``` is not the problem - I close the issue

**Comment by discordier** [comment]
Of course it is the problem, the frontend input type should not have been tags but radio!

**Comment by zonky2** [comment]
realy?!? look at https://github.com/MetaModels/filter_register/issues/8

the input type is in my mind irrelevant, because the template hasn't form element radio or checkbox

**Comment by discordier** [comment]
Yes, the standard implementation is simply still missing in this filter.
It was developed ad-hoc and has to get finished.

**Comment by zonky2** [comment]
> It was developed ad-hoc and has to get finished.

that´s thrue

**Comment by zonky2** [comment]
the input type is not the decisive factor - in version 2.2 there is an option whether one or more letters are filterable
